/**
 * Extracts the HugeIcons we actually use from @iconify-json/hugeicons into
 * src/lib/hugeicons.ts.
 *
 * Why not astro-icon? It drags @iconify/tools (a CJS build-time toolkit) into
 * the request path, which the Cloudflare dev module runner cannot load
 * ("module is not defined"). Generating a small typed map instead keeps the
 * worker bundle tiny and works identically in dev, build and production.
 *
 * Run after adding a name to ICONS:  npm run icons
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const ICONS = [
  'ai-chat-02',
  'archive-02',
  'arrow-down-01',
  'arrow-left-01',
  'arrow-right-01',
  'arrow-up-01',
  'arrow-up-right-01',
  'clock-01',
  'code-circle',
  'download-01',
  'file-01',
  'github-01',
  'link-02',
  'linkedin-01',
  'live-streaming-02',
  'mail-02',
  'moon-02',
  'new-twitter',
  'plus-sign',
  'sun-03',
];

const setPath = require.resolve('@iconify-json/hugeicons/icons.json');
const set = JSON.parse(readFileSync(setPath, 'utf8'));

const missing = ICONS.filter((name) => !set.icons[name]);
if (missing.length) {
  console.error(`Unknown HugeIcons names: ${missing.join(', ')}`);
  process.exit(1);
}

const width = set.width ?? 24;
const height = set.height ?? 24;

const entries = ICONS.map((name) => {
  const icon = set.icons[name];
  const body = icon.body.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `  '${name}': { body: '${body}', width: ${icon.width ?? width}, height: ${icon.height ?? height} },`;
}).join('\n');

const out = `// GENERATED by scripts/generate-icons.mjs, do not edit by hand.
// Source: @iconify-json/hugeicons v${set.info?.version ?? 'unknown'}

export type IconData = { body: string; width: number; height: number };

export const HUGEICONS = {
${entries}
} as const satisfies Record<string, IconData>;

export type IconName = keyof typeof HUGEICONS;
`;

mkdirSync(join(root, 'src/lib'), { recursive: true });
writeFileSync(join(root, 'src/lib/hugeicons.ts'), out, 'utf8');
console.log(`Wrote src/lib/hugeicons.ts with ${ICONS.length} icons.`);
